spring:
  application:
    name: paymentService

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: validate   # rely on Flyway, don?t auto-create tables
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration